# Generated by Django 3.0.8 on 2020-07-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
