# Generated by Django 3.0.8 on 2020-07-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_comment_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
