# Generated by Django 3.0.8 on 2020-07-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image_link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
