# Generated by Django 3.0.8 on 2020-08-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20200820_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('date_added',)},
        ),
    ]
