# Generated by Django 3.0.8 on 2020-09-03 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_auto_20200821_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='syllabus',
            field=models.CharField(default='Lesson syllabus', max_length=200),
        ),
        migrations.CreateModel(
            name='AdditionalMaterialLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('image', models.CharField(max_length=400)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson')),
            ],
        ),
    ]
