# Generated by Django 3.0.8 on 2020-09-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_lesson_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalmateriallesson',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalmateriallesson',
            name='image',
            field=models.ImageField(upload_to='lessons/static/lessons/images', verbose_name='Upload image'),
        ),
    ]
