# Generated by Django 3.0.8 on 2020-09-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_articles_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to='articles/images', verbose_name='Upload image'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image_link',
            field=models.ImageField(upload_to='lessons/images', verbose_name='Upload image'),
        ),
    ]
